#Usage
# ansible-playbook InstallOracleDBPSUPatch.yml --extra-vars "hosts=[EnterHosts] DBPSUZipFile=[DBPSUZip] DBPSUUnzipFolder=[DBPSUFolder]"
---
- hosts: '{{ hosts }}'
  gather_facts: no
  vars:
    patchDir: "/opt/Patch"
    oracleHome: "/opt/app/oracle/product/11.2.0/dbhome_1"
  tasks:
  
  - name: copy patch
    copy: src=../Files/{{ item }} dest={{ patchDir }}
    with_items:
     - '{{ DBPSUZipFile }}'

  - name: unzip DBPSU patch
    unarchive: src='{{ patchDir }}'/'{{ DBPSUZipFile }}' dest='{{ patchDir }}' copy=no

  - name: OPatch Check PreReqs
    shell: su - oracle -c "cd '{{ patchDir }}'/'{{ DBPSUUnzipFolder }}'; '{{ oracleHome }}'/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -ph ./"
    register: conflict_detection
    failed_when: "'Prereq \"checkConflictAgainstOHWithDetail\" passed.' not in conflict_detection.stdout"

  - name: Shutdown Oracle Instances
    shell: su - oracle -c "'{{ oracleHome }}'/bin/dbshut '{{ oracleHome }}'; '{{ oracleHome }}'/bin/emctl stop dbconsole; '{{ oracleHome }}'/bin/lsnrctl stop"

  - name: Install DBPSU Patch
    shell: su - oracle -c "cd '{{ patchDir }}'/'{{ DBPSUUnzipFolder }}'; '{{ oracleHome }}'/OPatch/opatch apply"
    register: apply_psu
    failed_when: "'Composite patch '{{ DBPSUUnzipFolder }}'  successfully applied.' not in apply_psu.stdout"

  - name: Startup Oracle Instances
    shell: su - oracle -c "'{{ oracleHome }}'/bin/lsnrctl start; '{{ oracleHome }}'/bin/dbstart '{{ oracleHome }}'; '{{ oracleHome }}'/bin/emctl start dbconsole;"

   - name: Run CatBundle
     shell: su - oracle -c "cd '{{ oracleHome }}'/rdbms/admin; echo exit | sqlplus / as sysdba @catbundle.sql psu apply;"
